# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
	git
	docker
	zsh-autosuggestions
	poetry
	zsh-syntax-highlighting
 	kubectl
 )

source $ZSH/oh-my-zsh.sh

# aliases
alias cat=bat
alias l='exa --icons'
alias ll='exa -l --icons'
alias la='exa -a --icons'
alias lla='exa -la --icons'
alias lt='exa --tree --icons'
alias nano='nano --linenumbers'
alias ipy='ipython'
alias btm='btm --color=gruvbox'
alias k=kubectl
alias dotdrop='~/works/my-dotfiles/dotdrop.sh'

# paths
export PATH="$HOME/.local/bin:$PATH"

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# starship
eval "$(starship init zsh)"

# pipx
autoload -U bashcompinit && bashcompinit
autoload -Uz compinit
compinit

export GPG_TTY=$(tty)
